// Fallback data for when database is empty or unavailable
// This ensures the website always displays content

import type { Tool, Category, Post, Course, Event, Group } from './database.types'

// =====================================================
// CATEGORIES
// =====================================================
export const FALLBACK_CATEGORIES: Category[] = [
  { id: '1', name: 'ChatGPT', slug: 'chatgpt', description: 'Hướng dẫn sử dụng ChatGPT từ cơ bản đến nâng cao', icon: '🤖', color: '#10a37f', order_index: 1, created_at: new Date().toISOString() },
  { id: '2', name: 'Claude AI', slug: 'claude-ai', description: 'Anthropic Claude - AI assistant mạnh mẽ cho coding và writing', icon: '🧠', color: '#7c3aed', order_index: 2, created_at: new Date().toISOString() },
  { id: '3', name: 'Midjourney & AI Art', slug: 'ai-art', description: 'Tạo hình ảnh với Midjourney, DALL-E, Stable Diffusion', icon: '🎨', color: '#ec4899', order_index: 3, created_at: new Date().toISOString() },
  { id: '4', name: 'Automation', slug: 'automation', description: 'Tự động hóa với Make, Zapier, n8n và AI', icon: '⚡', color: '#f59e0b', order_index: 4, created_at: new Date().toISOString() },
  { id: '5', name: 'AI cho Marketing', slug: 'ai-marketing', description: 'Content marketing, SEO, Ads với AI', icon: '📣', color: '#ef4444', order_index: 5, created_at: new Date().toISOString() },
  { id: '6', name: 'AI cho Developer', slug: 'ai-dev', description: 'GitHub Copilot, Cursor, AI coding assistants', icon: '💻', color: '#3b82f6', order_index: 6, created_at: new Date().toISOString() },
  { id: '7', name: 'Prompt Engineering', slug: 'prompt-engineering', description: 'Kỹ thuật viết prompt hiệu quả', icon: '✨', color: '#8b5cf6', order_index: 7, created_at: new Date().toISOString() },
  { id: '8', name: 'AI News & Trends', slug: 'ai-news', description: 'Tin tức và xu hướng AI mới nhất', icon: '📰', color: '#6366f1', order_index: 8, created_at: new Date().toISOString() },
  { id: '9', name: 'Case Study', slug: 'case-study', description: 'Case study thực tế từ các thành viên', icon: '📊', color: '#14b8a6', order_index: 9, created_at: new Date().toISOString() },
  { id: '10', name: 'Hỏi đáp', slug: 'hoi-dap', description: 'Đặt câu hỏi và nhận hỗ trợ từ cộng đồng', icon: '❓', color: '#f97316', order_index: 10, created_at: new Date().toISOString() },
]

// =====================================================
// TOOLS
// =====================================================
export const FALLBACK_TOOLS: Tool[] = [
  {
    id: '1',
    name: 'ChatGPT',
    slug: 'chatgpt',
    description: 'AI chatbot phổ biến nhất thế giới từ OpenAI. Có thể trò chuyện, viết content, code, phân tích dữ liệu và nhiều hơn nữa.',
    logo_url: null,
    website_url: 'https://chat.openai.com',
    category: 'llm',
    pricing: 'freemium',
    pricing_detail: 'Free: GPT-3.5 | Plus: $20/tháng (GPT-4)',
    features: ['Trò chuyện tự nhiên', 'Viết content', 'Code assistance', 'Phân tích file', 'Tạo hình ảnh DALL-E'],
    use_cases: ['Viết email, blog, báo cáo', 'Học ngôn ngữ mới', 'Brainstorm ý tưởng', 'Debug code'],
    pros: ['Dễ sử dụng', 'Đa năng', 'Cộng đồng lớn', 'Plugins phong phú'],
    cons: ['GPT-4 cần trả phí', 'Giới hạn tin nhắn', 'Có thể hallucinate'],
    rating: 4.8,
    is_featured: true,
    order_index: 1,
    created_at: new Date().toISOString(),
    updated_at: null
  },
  {
    id: '2',
    name: 'Claude',
    slug: 'claude',
    description: 'AI assistant từ Anthropic. Nổi bật với khả năng xử lý context dài, code chính xác và an toàn hơn.',
    logo_url: null,
    website_url: 'https://claude.ai',
    category: 'llm',
    pricing: 'freemium',
    pricing_detail: 'Free: Claude 3 Haiku | Pro: $20/tháng (Sonnet, Opus)',
    features: ['Context window 200K tokens', 'Code chính xác', 'An toàn, không harmful', 'Phân tích documents'],
    use_cases: ['Viết code dài', 'Phân tích tài liệu PDF', 'Research paper', 'Copywriting chuyên nghiệp'],
    pros: ['Context dài nhất', 'Code quality cao', 'Ít hallucinate', 'Artifacts hữu ích'],
    cons: ['Ít plugins hơn ChatGPT', 'Không tạo hình ảnh', 'Chưa có voice'],
    rating: 4.7,
    is_featured: true,
    order_index: 2,
    created_at: new Date().toISOString(),
    updated_at: null
  },
  {
    id: '3',
    name: 'Gemini',
    slug: 'gemini',
    description: 'AI từ Google với khả năng multimodal - hiểu text, hình ảnh, video và audio.',
    logo_url: null,
    website_url: 'https://gemini.google.com',
    category: 'llm',
    pricing: 'freemium',
    pricing_detail: 'Free: Gemini | Advanced: $20/tháng',
    features: ['Multimodal (text, image, video)', 'Tích hợp Google services', 'Real-time info'],
    use_cases: ['Research với Google', 'Phân tích hình ảnh', 'Tích hợp Gmail, Docs'],
    pros: ['Free mạnh', 'Tích hợp Google ecosystem', 'Multimodal tốt'],
    cons: ['Đôi khi chậm', 'Output ngắn hơn'],
    rating: 4.3,
    is_featured: true,
    order_index: 3,
    created_at: new Date().toISOString(),
    updated_at: null
  },
  {
    id: '4',
    name: 'Perplexity',
    slug: 'perplexity',
    description: 'AI search engine - trả lời câu hỏi với nguồn trích dẫn rõ ràng từ internet.',
    logo_url: null,
    website_url: 'https://perplexity.ai',
    category: 'llm',
    pricing: 'freemium',
    pricing_detail: 'Free: 5 Pro searches/ngày | Pro: $20/tháng',
    features: ['Search với citations', 'Real-time data', 'Academic mode', 'File upload'],
    use_cases: ['Research nhanh', 'Fact-checking', 'Tin tức mới nhất'],
    pros: ['Có nguồn trích dẫn', 'Thông tin real-time', 'Giao diện đẹp'],
    cons: ['Giới hạn Pro searches', 'Không chat dài'],
    rating: 4.5,
    is_featured: true,
    order_index: 4,
    created_at: new Date().toISOString(),
    updated_at: null
  },
  {
    id: '5',
    name: 'Midjourney',
    slug: 'midjourney',
    description: 'AI tạo hình ảnh chất lượng cao nhất hiện tại. Chạy qua Discord.',
    logo_url: null,
    website_url: 'https://midjourney.com',
    category: 'image',
    pricing: 'paid',
    pricing_detail: 'Basic: $10/tháng | Standard: $30/tháng | Pro: $60/tháng',
    features: ['Hình ảnh siêu đẹp', 'Nhiều style', 'Vary/Upscale', 'Style reference'],
    use_cases: ['Marketing visuals', 'Product mockup', 'Art concept', 'Social media content'],
    pros: ['Chất lượng tốt nhất', 'Style độc đáo', 'Cộng đồng active'],
    cons: ['Phải dùng Discord', 'Không edit được', 'Khó control chính xác'],
    rating: 4.9,
    is_featured: true,
    order_index: 5,
    created_at: new Date().toISOString(),
    updated_at: null
  },
  {
    id: '6',
    name: 'Make (Integromat)',
    slug: 'make',
    description: 'Nền tảng automation no-code mạnh mẽ. Kết nối hàng ngàn apps với nhau.',
    logo_url: null,
    website_url: 'https://make.com',
    category: 'automation',
    pricing: 'freemium',
    pricing_detail: 'Free: 1000 ops/tháng | Core: $9/tháng | Pro: $16/tháng',
    features: ['Visual workflow builder', '1000+ apps', 'Webhooks', 'HTTP requests'],
    use_cases: ['Lead automation', 'Social media posting', 'Data sync', 'Email workflows'],
    pros: ['Giao diện trực quan', 'Giá hợp lý', 'Nhiều apps', 'Flexible'],
    cons: ['Learning curve', 'Debugging khó', 'Giới hạn free'],
    rating: 4.6,
    is_featured: true,
    order_index: 6,
    created_at: new Date().toISOString(),
    updated_at: null
  },
  {
    id: '7',
    name: 'GitHub Copilot',
    slug: 'github-copilot',
    description: 'AI pair programmer từ GitHub/Microsoft. Autocomplete code trong IDE.',
    logo_url: null,
    website_url: 'https://github.com/features/copilot',
    category: 'coding',
    pricing: 'paid',
    pricing_detail: 'Individual: $10/tháng | Business: $19/user/tháng',
    features: ['Code autocomplete', 'Chat in IDE', 'Multi-language', 'Test generation'],
    use_cases: ['Viết code nhanh hơn', 'Learn new languages', 'Generate tests'],
    pros: ['Tích hợp IDE tốt', 'Nhanh', 'Multi-language'],
    cons: ['Subscription bắt buộc', 'Đôi khi sai', 'Privacy concerns'],
    rating: 4.6,
    is_featured: true,
    order_index: 7,
    created_at: new Date().toISOString(),
    updated_at: null
  },
  {
    id: '8',
    name: 'Cursor',
    slug: 'cursor',
    description: 'AI-first code editor. Fork từ VS Code với AI tích hợp sâu.',
    logo_url: null,
    website_url: 'https://cursor.sh',
    category: 'coding',
    pricing: 'freemium',
    pricing_detail: 'Free: 2000 completions | Pro: $20/tháng',
    features: ['AI chat trong editor', 'Codebase understanding', 'Multi-file edits', 'Terminal AI'],
    use_cases: ['Refactor lớn', 'Debug với AI', 'Code review', 'New projects'],
    pros: ['AI tích hợp sâu', 'Hiểu cả codebase', 'UI đẹp'],
    cons: ['Mới, còn bugs', 'Resource heavy', 'Subscription'],
    rating: 4.7,
    is_featured: true,
    order_index: 8,
    created_at: new Date().toISOString(),
    updated_at: null
  },
  {
    id: '9',
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    description: 'AI voice generation chất lượng cao. Clone voice, text-to-speech.',
    logo_url: null,
    website_url: 'https://elevenlabs.io',
    category: 'audio',
    pricing: 'freemium',
    pricing_detail: 'Free: 10K chars/tháng | Starter: $5/tháng | Creator: $22/tháng',
    features: ['Realistic voices', 'Voice cloning', 'Multiple languages', 'API access'],
    use_cases: ['Voiceover', 'Audiobooks', 'Video narration', 'Podcasts'],
    pros: ['Chất lượng tốt nhất', 'Voice clone tốt', 'Nhiều ngôn ngữ'],
    cons: ['Đắt cho volume lớn', 'Clone cần samples'],
    rating: 4.7,
    is_featured: false,
    order_index: 9,
    created_at: new Date().toISOString(),
    updated_at: null
  },
  {
    id: '10',
    name: 'Runway',
    slug: 'runway',
    description: 'AI video editing và generation. Gen-2 text-to-video, video-to-video.',
    logo_url: null,
    website_url: 'https://runwayml.com',
    category: 'video',
    pricing: 'freemium',
    pricing_detail: 'Free trial | Standard: $12/tháng | Pro: $28/tháng',
    features: ['Gen-2 text-to-video', 'Video-to-video', 'Image-to-video', 'Motion brush'],
    use_cases: ['Film production', 'Music videos', 'Social content', 'VFX'],
    pros: ['Cutting-edge tech', 'Creative freedom', 'Growing features'],
    cons: ['Credit system', 'Quality varies', 'Slow generation'],
    rating: 4.5,
    is_featured: false,
    order_index: 10,
    created_at: new Date().toISOString(),
    updated_at: null
  },
]

// =====================================================
// SAMPLE POSTS
// =====================================================
export const FALLBACK_POSTS: Partial<Post>[] = [
  {
    id: '1',
    title: 'Chào mừng đến với Alex Le AI Community!',
    slug: 'chao-mung-alex-le-ai',
    content: 'Đây là cộng đồng học AI cho người đi làm...',
    excerpt: 'Giới thiệu về cộng đồng Alex Le AI và hướng dẫn cho thành viên mới.',
    category_id: '1',
    required_tier: 'free',
    status: 'published',
    is_pinned: true,
    likes: 156,
    views: 2340,
    published_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    title: '5 Sai lầm phổ biến khi dùng ChatGPT',
    slug: '5-sai-lam-chatgpt',
    content: 'Những lỗi thường gặp và cách khắc phục...',
    excerpt: 'Những lỗi thường gặp khi sử dụng ChatGPT và cách khắc phục.',
    category_id: '1',
    required_tier: 'free',
    status: 'published',
    is_pinned: false,
    likes: 89,
    views: 1245,
    published_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    title: 'So sánh ChatGPT vs Claude vs Gemini',
    slug: 'so-sanh-chatgpt-claude-gemini',
    content: 'So sánh 3 AI chatbot phổ biến nhất...',
    excerpt: 'So sánh chi tiết ChatGPT, Claude và Gemini - ưu nhược điểm của từng tool.',
    category_id: '8',
    required_tier: 'free',
    status: 'published',
    is_pinned: false,
    likes: 67,
    views: 890,
    published_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    title: 'Case Study: Tiết kiệm 10 tiếng/tuần với Make',
    slug: 'case-study-make-automation',
    content: 'Chia sẻ cách tôi tự động hóa quy trình marketing...',
    excerpt: 'Chia sẻ cách tôi tự động hóa quy trình marketing và tiết kiệm 10 tiếng mỗi tuần.',
    category_id: '4',
    required_tier: 'free',
    status: 'published',
    is_pinned: false,
    likes: 124,
    views: 1567,
    published_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

// =====================================================
// COURSES
// =====================================================
export const FALLBACK_COURSES: Partial<Course>[] = [
  {
    id: '1',
    title: 'ChatGPT cho người mới bắt đầu',
    slug: 'chatgpt-co-ban',
    description: 'Học cách sử dụng ChatGPT từ A-Z. Từ tạo tài khoản, viết prompt cơ bản đến các tính năng nâng cao.',
    category_id: '1',
    required_tier: 'free',
    required_level: 1,
    duration_minutes: 120,
    lessons_count: 10,
    status: 'published',
  },
  {
    id: '2',
    title: '10 Cách dùng ChatGPT hàng ngày',
    slug: 'chatgpt-hang-ngay',
    description: 'Các use case thực tế: viết email, tóm tắt văn bản, dịch thuật, brainstorm ý tưởng.',
    category_id: '1',
    required_tier: 'free',
    required_level: 1,
    duration_minutes: 60,
    lessons_count: 5,
    status: 'published',
  },
  {
    id: '3',
    title: 'Prompt Engineering 101',
    slug: 'prompt-engineering-101',
    description: 'Kỹ thuật viết prompt hiệu quả: Chain of Thought, Few-shot, Role-playing và các framework phổ biến.',
    category_id: '7',
    required_tier: 'basic',
    required_level: 2,
    duration_minutes: 180,
    lessons_count: 12,
    status: 'published',
  },
  {
    id: '4',
    title: 'Claude AI Masterclass',
    slug: 'claude-masterclass',
    description: 'Sử dụng Claude AI hiệu quả: xử lý documents dài, code projects, và so sánh với ChatGPT.',
    category_id: '2',
    required_tier: 'basic',
    required_level: 3,
    duration_minutes: 120,
    lessons_count: 8,
    status: 'published',
  },
  {
    id: '5',
    title: 'AI Automation với Make',
    slug: 'ai-automation-make',
    description: 'Xây dựng workflows tự động với Make.com và AI. Từ cơ bản đến advanced scenarios.',
    category_id: '4',
    required_tier: 'premium',
    required_level: 4,
    duration_minutes: 240,
    lessons_count: 15,
    status: 'published',
  },
  {
    id: '6',
    title: 'Midjourney Pro Guide',
    slug: 'midjourney-pro',
    description: 'Tạo hình ảnh chuyên nghiệp với Midjourney. Parameters, styles, workflows cho marketing.',
    category_id: '3',
    required_tier: 'premium',
    required_level: 4,
    duration_minutes: 180,
    lessons_count: 12,
    status: 'published',
  },
]

// =====================================================
// EVENTS
// =====================================================
export const FALLBACK_EVENTS: Partial<Event>[] = [
  {
    id: '1',
    title: 'Weekly Q&A: Hỏi đáp về AI',
    description: 'Buổi livestream hàng tuần để trả lời mọi câu hỏi về AI, ChatGPT, Claude, và các tools khác.',
    event_type: 'livestream',
    start_time: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    duration_minutes: 60,
    meeting_url: 'https://meet.google.com/abc-defg-hij',
    status: 'published',
  },
  {
    id: '2',
    title: 'Workshop: Automation với Make.com',
    description: 'Hands-on workshop xây dựng automation workflow từ đầu. Mang theo laptop!',
    event_type: 'workshop',
    start_time: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    duration_minutes: 120,
    meeting_url: 'https://zoom.us/j/123456789',
    status: 'published',
  },
  {
    id: '3',
    title: 'Webinar: AI Trends',
    description: 'Tổng hợp xu hướng AI quan trọng và predictions cho năm tới.',
    event_type: 'webinar',
    start_time: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    duration_minutes: 90,
    meeting_url: 'https://meet.google.com/xyz-uvwx-rst',
    status: 'published',
  },
]

// =====================================================
// GROUPS
// =====================================================
export const FALLBACK_GROUPS: Partial<Group>[] = [
  {
    id: '1',
    name: 'Alex Le AI',
    slug: 'alex-le-ai',
    description: 'Cộng đồng học AI cho người đi làm',
    about: 'Cộng đồng học AI cho người đi làm. Chia sẻ case study thực tế về ChatGPT, Claude, Midjourney, Make và các AI tools khác.',
    icon_emoji: '🚀',
    color: '#1877f2',
    privacy: 'public',
    member_count: 1247,
    post_count: 892,
    course_count: 15,
    is_featured: true,
    required_tier: 'free',
    created_at: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    name: 'ChatGPT Mastery',
    slug: 'chatgpt-mastery',
    description: 'Nhóm chuyên sâu về ChatGPT và OpenAI APIs. Prompt engineering, GPT-4, plugins, custom GPTs.',
    about: 'Nơi chia sẻ kinh nghiệm sử dụng ChatGPT trong công việc thực tế. Từ viết content, code, đến xây dựng automation workflows.',
    icon_emoji: '🤖',
    color: '#10a37f',
    privacy: 'public',
    member_count: 856,
    post_count: 432,
    course_count: 8,
    is_featured: true,
    required_tier: 'free',
    created_at: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    name: 'AI Automation Pro',
    slug: 'ai-automation-pro',
    description: 'Tự động hóa mọi thứ với Make, Zapier, n8n kết hợp AI. Tiết kiệm hàng chục giờ mỗi tuần.',
    about: 'Nhóm dành cho những ai muốn tự động hóa quy trình làm việc. Chia sẻ templates, workflows, và case studies thực tế.',
    icon_emoji: '⚡',
    color: '#f59e0b',
    privacy: 'public',
    member_count: 534,
    post_count: 267,
    course_count: 5,
    is_featured: true,
    required_tier: 'free',
    created_at: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    name: 'AI Art & Design',
    slug: 'ai-art-design',
    description: 'Midjourney, DALL-E, Stable Diffusion, Runway. Tạo hình ảnh và video chuyên nghiệp với AI.',
    about: 'Khám phá thế giới AI Art. Chia sẻ prompt, techniques, workflows cho Midjourney, DALL-E, và các công cụ tạo ảnh AI.',
    icon_emoji: '🎨',
    color: '#ec4899',
    privacy: 'public',
    member_count: 423,
    post_count: 198,
    course_count: 4,
    is_featured: false,
    required_tier: 'free',
    created_at: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    name: 'AI Coding Club',
    slug: 'ai-coding-club',
    description: 'GitHub Copilot, Cursor, Claude Code. Tăng tốc coding 10x với AI assistants.',
    about: 'Nhóm dành cho developers muốn tận dụng AI để code nhanh hơn, hiệu quả hơn.',
    icon_emoji: '💻',
    color: '#3b82f6',
    privacy: 'public',
    member_count: 312,
    post_count: 145,
    course_count: 3,
    is_featured: false,
    required_tier: 'basic',
    created_at: new Date(Date.now() - 80 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '6',
    name: 'Premium AI Masterclass',
    slug: 'premium-ai-masterclass',
    description: 'Nhóm VIP với nội dung chuyên sâu, mentoring 1-1, và early access tính năng mới.',
    about: 'Nội dung độc quyền cho Premium members. Advanced techniques, live workshops, và hỗ trợ trực tiếp từ experts.',
    icon_emoji: '👑',
    color: '#8b5cf6',
    privacy: 'private',
    member_count: 89,
    post_count: 67,
    course_count: 6,
    is_featured: true,
    required_tier: 'premium',
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

// =====================================================
// TOP MEMBERS (for sidebar)
// =====================================================
export const FALLBACK_TOP_MEMBERS = [
  { id: '1', full_name: 'Alex Le', username: 'alexle', points: 12500, role: 'admin' as const, subscription_tier: 'premium' as const },
  { id: '2', full_name: 'Minh Trần', username: 'minhtran', points: 8900, role: 'member' as const, subscription_tier: 'premium' as const },
  { id: '3', full_name: 'Lan Nguyễn', username: 'lannguyen', points: 7200, role: 'member' as const, subscription_tier: 'basic' as const },
  { id: '4', full_name: 'Đức Phạm', username: 'ducpham', points: 5100, role: 'member' as const, subscription_tier: 'basic' as const },
  { id: '5', full_name: 'Hoa Võ', username: 'hoavo', points: 3200, role: 'member' as const, subscription_tier: 'free' as const },
]
